"""The persistent models, and the connection to the database holding them.

Deliberately outside the API package. The pass that reconciles what each pod
has loaded against what its tenant should be serving, the worker that builds
artifacts, and the hydration a process does at boot all read and write these
tables, and none of them is part of the web layer. Left inside ``api``, every
one of those would import from it — backwards, and the reconcile pass is next.

The API imports *from* here. Nothing here imports the API.
"""

from .control_plane import (
    ARTIFACT_ACTIVE,
    ARTIFACT_BUILDING,
    ARTIFACT_FAILED,
    ARTIFACT_READY,
    ARTIFACT_SUPERSEDED,
    ARTIFACT_JOB_FK,
    ApiKey,
    Base,
    CIRCULAR_FOREIGN_KEYS,
    CONTROL_PLANE_MODELS,
    CONTROL_PLANE_TABLES,
    DEFAULT_SCOPES,
    GraphArtifact,
    IngestJob,
    JOB_ARTIFACT_FK,
    JOB_COMPILING,
    JOB_COMPLETED,
    JOB_COMPUTING,
    JOB_FAILED,
    JOB_FETCHING,
    JOB_IN_FLIGHT,
    JOB_QUEUED,
    JOB_REGISTERED,
    JOB_SWAPPED,
    JOB_UPLOADING,
    LOAD_FAILED,
    LOAD_PULLING,
    LOAD_READY,
    ORGANIZATION_ARTIFACT_FK,
    Organization,
    Pod,
    POD_BOOTING,
    POD_DEAD,
    POD_DRAINING,
    POD_READY,
    PodAssignment,
    Repository,
    create_control_plane_schema,
)
from .graph_store import (
    EntityEdge,
    EntityNode,
    GRAPH_STORE_MODELS,
    GRAPH_STORE_TABLES,
    create_graph_store_schema,
    ensure_graph_store_schema,
    upsert_edges,
    upsert_nodes,
)
from .database import (
    CONTROL_PLANE_URL_VARIABLE,
    DATABASE_URL_VARIABLE,
    ControlPlaneNotConfigured,
    as_url,
    control_plane_sessions,
    control_plane_url,
    create_control_plane_engine,
)

__all__ = [
    "ApiKey",
    "create_graph_store_schema",
    "EntityEdge",
    "EntityNode",
    "ensure_graph_store_schema",
    "GRAPH_STORE_MODELS",
    "GRAPH_STORE_TABLES",
    "upsert_edges",
    "upsert_nodes",
    "ARTIFACT_ACTIVE",
    "ARTIFACT_BUILDING",
    "ARTIFACT_FAILED",
    "ARTIFACT_JOB_FK",
    "ARTIFACT_READY",
    "ARTIFACT_SUPERSEDED",
    "as_url",
    "Base",
    "CIRCULAR_FOREIGN_KEYS",
    "CONTROL_PLANE_MODELS",
    "CONTROL_PLANE_TABLES",
    "CONTROL_PLANE_URL_VARIABLE",
    "control_plane_sessions",
    "control_plane_url",
    "ControlPlaneNotConfigured",
    "create_control_plane_engine",
    "create_control_plane_schema",
    "DATABASE_URL_VARIABLE",
    "DEFAULT_SCOPES",
    "GraphArtifact",
    "IngestJob",
    "JOB_ARTIFACT_FK",
    "JOB_COMPILING",
    "JOB_COMPLETED",
    "JOB_COMPUTING",
    "JOB_FAILED",
    "JOB_FETCHING",
    "JOB_IN_FLIGHT",
    "JOB_QUEUED",
    "JOB_REGISTERED",
    "JOB_SWAPPED",
    "JOB_UPLOADING",
    "LOAD_FAILED",
    "LOAD_PULLING",
    "LOAD_READY",
    "ORGANIZATION_ARTIFACT_FK",
    "Organization",
    "Pod",
    "POD_BOOTING",
    "POD_DEAD",
    "POD_DRAINING",
    "POD_READY",
    "PodAssignment",
    "Repository",
]
